version: "3.8"

services:
  nginx:
    build:
      context: ./
      dockerfile: ./server/nginx.dockerfile
    container_name: nginx-container
    volumes:
      - ./server/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./server/nginx/api.dev.conf:/etc/nginx/api.conf
      - ./server/nginx/media.dev.conf:/etc/nginx/media.conf
      - ./server/nginx/app.dev.conf:/etc/nginx/app.conf
      - ./server/nginx/parts/fastcgi.conf:/etc/nginx/parts/fastcgi.conf
      - ./api:/var/www/api
      - ./media:/var/www/media
      - ./server/logs:/var/log/nginx
    ports:
      - "4201:4201"
      - "4202:4202"
      - "4203:4203"
    depends_on:
      - php
      - angular

  php:
    build:
      context: ./
      dockerfile: ./server/php.dockerfile
    platform: "linux/arm64/v8"
    container_name: php-container
    volumes:
      - ./api:/var/www/api
      - ./media:/var/www/media
      - ./api/Config/secretDatas.dev.json:/var/www/api/Config/secretDatas.json
      - ./server/php.ini:/usr/local/etc/php/php.ini
      - ./server/fill-tables/:/var/www/server/fill-tables
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=online_dreams_diary
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "sleep 5 && php /var/www/server/fill-tables/fill-tables.dev.php && php-fpm"
    restart: always

  mysql:
    image: mysql:8.0
    platform: "linux/arm64/v8"
    container_name: mysql-container
    volumes:
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online_dreams_diary
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    restart: always
    command: --innodb_use_native_aio=0

  angular:
    image: node:18-alpine
    container_name: angular-container
    volumes:
      - ./client:/var/www/client
      - /var/www/client/node_modules
    working_dir: /var/www/client
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start:docker"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4204:80"
    restart: always